# Generated by Django 3.2.6 on 2021-12-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrappedData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amezondata',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flipkartdata',
            name='original_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flipkartdata',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flipkartdata',
            name='ratting',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
