# Generated by Django 4.0 on 2021-12-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrappedData', '0002_auto_20211225_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='amezondata',
            name='ratting',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
