# Generated by Django 4.0 on 2021-12-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrappedData', '0003_amezondata_ratting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_files')),
            ],
        ),
    ]
